'use client';

// The model card — renders the REAL ROC curve from lib/radiomics-model.json (generated by the
// trained classifier, not hand-drawn) alongside the datasets, the training pipeline, and the honest
// accuracy. This is "show the actual radiomics model," the moat other teams can't stand up.

import model from '@/lib/radiomics-model.json';

const W = 320;
const H = 300;
const P = 40;
const px = (fpr: number) => P + fpr * (W - 2 * P);
const py = (tpr: number) => H - P - tpr * (H - 2 * P);

const DATASETS = [
  {
    name: 'GLENDA v1.5',
    role: 'Trained on',
    detail: 'Real laparoscopy frames — 500 pathology / 5,490 no-pathology (n=5,990).',
    cite: 'Leibetseder et al., MMM 2020 · ITEC, Univ. Klagenfurt',
    href: 'http://ftp.itec.aau.at/datasets/GLENDA/',
  },
  {
    name: 'UT-EndoMRI',
    role: 'Production path',
    detail: 'Same texture pipeline on patient-level pelvic MRI (133 real annotated cases).',
    cite: 'Zenodo — open access',
    href: 'https://zenodo.org/records/10574745',
  },
  {
    name: 'MMOTU',
    role: 'Ultrasound arm',
    detail: 'Multi-modal ovarian ultrasound — the generalization surface.',
    cite: 'Zhao et al. — open dataset',
    href: 'https://github.com/cv516Buaa/MMOTU_DS2Net',
  },
];

export function ModelCard() {
  const roc = model.roc as [number, number][];
  const rocPath = roc.map(([f, t], i) => `${i ? 'L' : 'M'}${px(f).toFixed(1)},${py(t).toFixed(1)}`).join(' ');

  return (
    <div className="modelcard">
      <figure className="roc-fig">
        <svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label={`ROC curve, area under curve ${model.roc_auc}`}>
          {/* frame */}
          <rect x={P} y={P} width={W - 2 * P} height={H - 2 * P} className="roc-frame" />
          {/* gridlines */}
          {[0.25, 0.5, 0.75].map((g) => (
            <g key={g}>
              <line x1={px(g)} y1={py(0)} x2={px(g)} y2={py(1)} className="roc-grid" />
              <line x1={px(0)} y1={py(g)} x2={px(1)} y2={py(g)} className="roc-grid" />
            </g>
          ))}
          {/* chance diagonal */}
          <line x1={px(0)} y1={py(0)} x2={px(1)} y2={py(1)} className="roc-diag" />
          {/* the real curve + fill */}
          <path d={`${rocPath} L${px(1).toFixed(1)},${py(0).toFixed(1)} Z`} className="roc-fill" />
          <path d={rocPath} className="roc-curve" />
          {/* axis labels */}
          <text x={W / 2} y={H - 10} className="roc-axis" textAnchor="middle">
            False-positive rate
          </text>
          <text x={12} y={H / 2} className="roc-axis" textAnchor="middle" transform={`rotate(-90 12 ${H / 2})`}>
            True-positive rate
          </text>
          <text x={px(0.52)} y={py(0.34)} className="roc-auc">
            AUC {model.roc_auc}
          </text>
        </svg>
        <figcaption>
          Out-of-fold ROC, 5-fold stratified CV · real GLENDA data · AP {model.average_precision} at{' '}
          {(model.prevalence * 100).toFixed(1)}% prevalence
        </figcaption>
      </figure>

      <div className="model-detail">
        <div className="model-metrics">
          <div className="mm">
            <div className="mm-v">{model.roc_auc}</div>
            <div className="mm-l">ROC-AUC (pooled out-of-fold)</div>
          </div>
          <div className="mm">
            <div className="mm-v">
              {model.fold_auc_mean}
              <span className="mm-pm"> ±{model.fold_auc_std}</span>
            </div>
            <div className="mm-l">per-fold, 5-fold CV</div>
          </div>
          <div className="mm">
            <div className="mm-v">{model.average_precision}</div>
            <div className="mm-l">avg precision (imbalanced)</div>
          </div>
        </div>

        <div className="model-pipe">
          <span className="label-sig">Pipeline — real features, not a hardcoded label</span>
          <p>
            scikit-image <b>GLCM + first-order texture</b> (12 features — the family PyRadiomics computes) →{' '}
            <b>RandomForest</b> (300 trees, class-weight balanced) → 5-fold stratified CV, out-of-fold scoring (no
            leakage). Top signal: <span className="token">fo_entropy</span> <span className="token">glcm_homogeneity</span>{' '}
            <span className="token">fo_p10</span>.
          </p>
        </div>

        <div className="model-data">
          {DATASETS.map((d) => (
            <div key={d.name} className="md-row">
              <span className="md-tag">{d.role}</span>
              <span className="md-name">{d.name}</span>
              <span className="md-detail">
                {d.detail}{' '}
                <a className="md-cite" href={d.href} target="_blank" rel="noreferrer">
                  {d.cite} ↗
                </a>
              </span>
            </div>
          ))}
        </div>

        <p className="model-caveat">
          Reported honestly: frame-level, single dataset, no external validation yet — endometriosis radiomics is
          research-grade across the literature. We frame the re-read as <b>investigational decision-support</b>, never
          autonomous diagnosis.
        </p>
      </div>
    </div>
  );
}
